"""Generate the README comparison directly from the completed WikiText report.

Run from any directory: python docs/figures/readme_figures.py
Dependencies are provided by the project's [research] installation extra.
This reads published observations and never evaluates or selects a checkpoint.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np


ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "public/research/test-results.json"
DESTINATION = Path(__file__).resolve().parent
ORDER = ("flm", "gru", "transformer")
LABELS = {"flm": "FLM", "gru": "GRU", "transformer": "Transformer"}


def main() -> None:
    payload = SOURCE.read_bytes()
    report = json.loads(payload)
    assert report["dataset"] == "WikiText-2 raw"
    aggregates = {row["variant"]: row for row in report["aggregates"]}
    values = {}
    for model in ORDER:
        runs = sorted(
            (row for row in report["runs"] if row["variant"] == model),
            key=lambda row: row["seed"],
        )
        assert [row["seed"] for row in runs] == [42, 43]
        assert all(row["checkpoint_step"] == 6000 for row in runs)
        assert all(row["score"]["bytes"] == 1287656 for row in runs)
        assert all(len(row["score"]["documents"]) == 60 for row in runs)
        scores = np.array([row["score"]["bits_per_byte"] for row in runs])
        assert np.isfinite(scores).all()
        assert abs(scores.mean() - aggregates[model]["mean_bpb"]) < 1e-12
        values[model] = scores

    plt.rcParams.update({
        "font.family": "DejaVu Sans",
        "font.size": 11,
        "svg.fonttype": "none",
        "svg.hashsalt": "flm-readme-wikitext-v1",
        "axes.edgecolor": "#c8c1b5",
        "text.color": "#302f29",
        "axes.labelcolor": "#302f29",
        "xtick.color": "#625e55",
        "ytick.color": "#302f29",
    })
    fig, ax = plt.subplots(figsize=(10, 4.45), facecolor="#faf8f4")
    ax.set_facecolor("#faf8f4")
    fig.subplots_adjust(left=.17, right=.80, top=.72, bottom=.24)
    fig.text(.045, .90, "WikiText-2 · completed test comparison", fontsize=19, weight="bold")
    fig.text(.045, .82, "Two training seeds · same tokenizer, data and 6,000-update budget", fontsize=11)
    for y, model in zip((2, 1, 0), ORDER):
        scores = values[model]
        color = "#ad4b20" if model == "flm" else "#487568"
        ax.scatter(scores[0], y + .11, marker="o", s=47, color=color, zorder=3)
        ax.scatter(scores[1], y - .11, marker="s", s=42, facecolors="none", edgecolors=color, linewidth=1.5, zorder=3)
        ax.scatter(scores.mean(), y, marker="D", s=33, color="#302f29", zorder=4)
        ax.text(1.015, y, f"{scores.mean():.4f}", transform=ax.get_yaxis_transform(), va="center", fontsize=14, weight="bold", color=color)
    ax.text(1.015, 2.58, "Mean BPB", transform=ax.get_yaxis_transform(), fontsize=10, color="#625e55")
    ax.set_yticks([2, 1, 0], [LABELS[model] for model in ORDER])
    ax.set_ylim(-.55, 2.55)
    ax.set_xlim(1.80, 2.05)
    ax.set_xticks(np.arange(1.80, 2.051, .05))
    ax.set_xlabel("Test bits per byte · lower is better", labelpad=11)
    ax.tick_params(axis="y", length=0, pad=12)
    ax.grid(axis="x", color="#ded8cf", linewidth=.8)
    ax.set_axisbelow(True)
    for edge in ("top", "right", "left"):
        ax.spines[edge].set_visible(False)
    fig.text(.045, .09, "● Seed 42     □ Seed 43     ◆ Two-seed mean", fontsize=10)
    fig.text(.045, .038, "All six selected checkpoints · 60 test articles each · individual observations, no uncertainty interval", fontsize=9, color="#625e55")
    provenance = (
        "Source: public/research/test-results.json; SHA-256: "
        + hashlib.sha256(payload).hexdigest()
        + ". Points are individual training seeds 42 and 43; diamonds are their arithmetic means. "
        "No confidence interval is shown. Generated by docs/figures/readme_figures.py."
    )
    for extension in ("svg", "png"):
        metadata = {"Title": "FLM: completed WikiText comparison", "Description": provenance}
        if extension == "svg":
            metadata["Date"] = None
        else:
            metadata["Software"] = "Matplotlib"
        target = DESTINATION / f"readme-wikitext.{extension}"
        fig.savefig(target, dpi=180, metadata=metadata)
        if extension == "svg":
            # Matplotlib adds spaces before line breaks inside path attributes.
            target.write_text(
                "\n".join(line.rstrip() for line in target.read_text(encoding="utf-8").splitlines()) + "\n",
                encoding="utf-8",
                newline="\n",
            )
        print(target.relative_to(ROOT))
    plt.close(fig)


if __name__ == "__main__":
    main()
