"""Derive paper tables from the complete audited BabyLM records, without inference."""
from pathlib import Path
import hashlib
import json
import shutil

from babylm_result_tables import collect

ROOT = Path(__file__).resolve().parents[1]


def main():
    report = collect(ROOT)
    frozen = ROOT / 'reports/babylm/tables-v1/tables.json'
    if report != json.loads(frozen.read_text(encoding='utf8')):
        raise ValueError('The complete audited table snapshot changed')
    values = {(r['scale'], r['variant'], r['component'], r['subset']): r
              for r in report['seed_aggregates']}
    rows = []
    for scale in ('10m', '100m'):
        for variant, label in (('flm', 'FLM'), ('gru', 'GRU'), ('transformer', 'Transformer')):
            official = values[scale, variant, 'all', 'official']
            filtered = values[scale, variant, 'all', 'overlap_filtered']
            rows.append(f"{scale.upper()} & {label} & {official['mean_bpb']:.6f} & "
                        f"{official['seed_standard_deviation']:.6f} & {filtered['mean_bpb']:.6f} \\\\")
    digest = lambda p: hashlib.sha256(p.read_bytes()).hexdigest()
    include = ROOT / 'papers/babylm-measured.tex'
    include.write_text('% Generated by scripts/babylm_paper_data.py; complete-study arithmetic only.\n'
        + '% tables.json SHA-256: ' + digest(frozen) + '\n'
        + '\\newcommand{\\BabyLMPooledRows}{%\n' + '\n'.join(rows) + '\n}\n', encoding='utf8', newline='\n')
    figure_manifest = json.loads((ROOT/'reports/babylm/figures-v1/manifest.json').read_text())
    outputs = [include]
    for name in ('babylm-pooled.png', 'babylm-components.png'):
        source = ROOT/'reports/babylm/figures-v1'/name
        if digest(source) != figure_manifest[name]['sha256']:
            raise ValueError('Reviewed figure changed: '+name)
        target = ROOT/'papers/figures'/name
        shutil.copyfile(source, target); outputs.append(target)
    record = dict(scope='Complete-record arithmetic audit and exact reviewed-figure copies; no inference, retraining or bootstrap replication.',
        input_sha256={str(frozen.relative_to(ROOT)).replace('\\','/'): digest(frozen)},
        generator_sha256=digest(Path(__file__)),
        output_sha256={p.relative_to(ROOT).as_posix(): digest(p) for p in outputs})
    target = ROOT/'reports/babylm/paper-inputs-v1.json'
    target.write_text(json.dumps(record, indent=2)+'\n', encoding='utf8', newline='\n')
    print('Verified complete tables and generated six pooled paper rows with two reviewed figures.')


if __name__ == '__main__':
    main()
