"""Generate paper tables from the complete, replay-verified feedback candidate."""
from pathlib import Path
import hashlib
import json
import math
import shutil

ROOT = Path(__file__).resolve().parents[1]
NAMES = dict(initial='Untrained', bptt='BPTT', reservoir='Fixed core', eligibility='Eligibility', scripted='Scripted reference')


def main():
    folder = ROOT / 'output/closed-loop-release'
    release = json.loads((ROOT / 'reports/embodiment/closed-loop/release-candidate.json').read_text())
    for name, digest in release['files'].items():
        if hashlib.sha256((folder / name).read_bytes()).hexdigest() != digest:
            raise ValueError('Feedback candidate changed: ' + name)
    report = json.loads((folder / 'closed-loop.json').read_text())
    if not report['complete'] or len(report['rows']) != 27 or not report['repeat_arrays_exact']:
        raise ValueError('A complete physical study is required for the paper')
    rows = {row['case']['label']: row for row in report['rows']}
    text = ['% Generated by scripts/feedback_paper_data.py; do not hand-edit measurements.']
    text.append(r'\newcommand{\FeedbackErrorRows}{%')
    for model, name in NAMES.items():
        for mode in ('live',) if model == 'scripted' else ('live', 'frozen'):
            values = [math.degrees(rows[f'{model}-{mode}-{scenario}']['metrics']['mean_absolute_bearing_error_rad']) for scenario in ('positive', 'negative', 'switch')]
            text.append(name + ' & ' + mode.capitalize() + ' & ' + ' & '.join(f'{value:.2f}' for value in values) + r' \\')
    text.append('}')
    text.append(r'\newcommand{\FeedbackContrastRows}{%')
    for model, name in NAMES.items():
        if model == 'scripted': continue
        values = [next(row['live_minus_frozen_error_rad'] for row in report['contrasts'] if row['model'] == model and row['scenario'] == scenario) for scenario in ('positive', 'negative', 'switch')]
        text.append(name + ' & ' + ' & '.join(f'{math.degrees(value):+.2f}' for value in values) + r' \\')
    text.append('}')
    equivalent = sum(rows[f'{model}-live-{scenario}']['physical_qpos_sha256'] == rows[f'scripted-live-{scenario}']['physical_qpos_sha256'] for model in ('bptt', 'reservoir', 'eligibility') for scenario in ('positive', 'negative', 'switch'))
    text.append(r'\newcommand{\FeedbackEquivalentCount}{' + str(equivalent) + '}')
    distinct = len(set(row['physical_qpos_sha256'] for row in rows.values()))
    text.append(r'\newcommand{\FeedbackDistinctPaths}{' + str(distinct) + '}')
    trace = rows['eligibility-live-switch']['metrics']
    for name, value in [('FeedbackSwitchError', math.degrees(trace['mean_absolute_bearing_error_rad'])), ('FeedbackSwitchDistance', trace['final_target_distance_mm']), ('FeedbackPhaseOne', trace['phase_progress'][0]['progress_toward_target_mm']), ('FeedbackPhaseTwo', trace['phase_progress'][1]['progress_toward_target_mm'])]:
        text.append('\\newcommand{\\' + name + '}{' + f'{value:.2f}' + '}')
    (ROOT / 'papers/feedback-measured.tex').write_text('\n'.join(text) + '\n', encoding='utf8')
    for name in ('closed-loop-switch.png', 'closed-loop-neural.png'):
        shutil.copyfile(folder / name, ROOT / 'papers/figures' / name)
    inputs = dict(candidate_json_sha256=hashlib.sha256((folder / 'closed-loop.json').read_bytes()).hexdigest(),
        identity_sha256=report['identity_sha256'], complete_conditions=27,
        trained_live_paths_identical_to_scripted=equivalent, distinct_recorded_physical_paths=distinct,
        generator_sha256=hashlib.sha256(Path(__file__).read_bytes()).hexdigest())
    (ROOT / 'reports/embodiment/closed-loop/paper-inputs.json').write_text(json.dumps(inputs, indent=2) + '\n')
    print(json.dumps(inputs, indent=2))


if __name__ == '__main__':
    main()
